### ISSUE TITLE
PERMIT_DOCKER=network does not extent to custom network

### ISSUE THREAD

**Issue by fbartels** [tomav/docker-mailserver#1079]
Reading through the description of PERMIT_DOCKER it sounds like `network` has the furthest reach, but setting the option to it does not allow sending from other containers in the same network (mail connections are subject to greylisting).

## Context
I am working on a docker-compose file that uses this image for the mta part. The wip is located at https://github.com/fbartels/kopano-docker/tree/compose. As part of the compose file a customer docker network is created that both docker-mailserver and the mail sending part of my application share the same network. when now trying to send a mail from my application this mail ends up in greylisting, while I would have expected (by setting `permit_docker=network`) that my application is part of mynetworks.

## Expected Behavior
the container kspooler should have been part of mynetworks

## Actual Behavior
its not part of mynetworks

## Possible Fix
do not set a fixed ip in https://github.com/tomav/docker-mailserver/blob/cc56b4f89ef854273fe0c33b87f94812f3b5cb71/target/start-mailserver.sh#L980-L984, but also use container_network

btw. instead of permit_docker=network, this actually works with permit_docker=host

## Steps to Reproduce
1. checkout project from above
2. run setup.sh (accept all defaults)
3. docker-compose up
4. go to webapp.kopano.com, login with user1/user1, try to send a mail to user1@kopano.demo 

## Your Environment
i don't think this is relevant

**Comment by martin-schulze-vireso** [comment]
@fbartels I ran into this issue while using the kopano-docker project mentioned above.
In my setup there are three networks on this container.

Two of them have 192.168.xxx.0/24 adresses. These will not be matched by 172.16.0.0/12. Unfortunately, using `PERMIT_DOCKER=host` does not fix this since the eth0 has 172.27.0.0/16 in this setup.

I think the cleanest solution would be for `PERMIT_DOCKER=network` to loop over all interfaces and add all those networks as trusted.

A possible workaround would be to force all networks into the 172.16-31 space which is in 172.16.0.0/12

**Comment by fbartels** [comment]
@martin-schulze-vireso hm.. I must say I don't think I have seen this issue for quite a while (although I am not sure what exactly I have changed in my compose file since then).

**Comment by martin-schulze-vireso** [comment]
@fbartels Well, your workaround from the issue description is still in the compose.yml so I assume it works because of this?

**Comment by fbartels** [comment]
Ah, yes indeed.

**Comment by martin-schulze-vireso** [comment]
I added #1185 which might should solve this issue.

**Comment by martin-schulze-vireso** [comment]
@fbartels With the PR being merged now your usecase should be fully supported now.

**Comment by fbartels** [comment]
Hi @martin-schulze-vireso,

I made a quick test (see https://github.com/zokradonh/kopano-docker/pull/210 for details) with some modifications to https://github.com/zokradonh/kopano-docker/ and a local build of the current master branch. But unfortunately I still get `Recipient address rejected: Delayed by postgrey. (will be retried)`.

**Comment by martin-schulze-vireso** [comment]
Having a quick look on your code I see the following:

1. instead of changing the behavior of `PERMIT_DOCKER=network` I added `PERMIT_DOCKER=connected-networks` to avoid changing the meaning of existing code, so you need to use the latter to get the new functionality.
2. Is the testing tag built locally or pulled from dockerhub? If the latter, does it include the PR's code?

**Comment by fbartels** [comment]
Ah, I missed the new option, but that also explains why there recently a test for connected-network started failing on my system..

Will retest later.

**Comment by fbartels** [comment]
Still won't work. but instead of the message landing in greylisting, there is now a lookup error and no mails are sent:

```
mail_1                   | Aug  6 08:20:48 mail postfix/postscreen[1717]: CONNECT from [172.19.0.12]:52660 to [172.19.0.3]:25
mail_1                   | Aug  6 08:20:48 mail postfix/postscreen[1717]: warning: postscreen_access_list: non-null host address bits in "127.0.0.1/8", perhaps you should use "127.0.0.0/8" instead
mail_1                   | Aug  6 08:20:48 mail postfix/postscreen[1717]: warning: postscreen_access_list: permit_mynetworks: mynetworks lookup error -- ignoring the remainder of this access list
kopano_spooler_1         | Tue Aug  6 08:20:54 2019: [error  ] [   35] RCPT line gave SMTP error: 451 4.3.0 <kopano_kopano_spooler_1.kopano_kopano-net[172.19.0.12]>: Temporary lookup failure. (will be retried)
kopano_spooler_1         | Tue Aug  6 08:20:54 2019: [error  ] [   35] SMTP: Error while executing command 'DATA'. Response: 554 5.5.1 Error: no valid recipients
kopano_spooler_1         | Tue Aug  6 08:20:54 2019: [warning] [   35] E-mail for user user1 could not be sent, notifying user: cancel message (40580)
mail_1                   | Aug  6 08:20:54 mail postfix/postscreen[1717]: PASS NEW [172.19.0.12]:52660
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: connect from kopano_kopano_spooler_1.kopano_kopano-net[172.19.0.12]
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: warning: smtpd_client_event_limit_exceptions: non-null host address bits in "127.0.0.1/8", perhaps you should use "127.0.0.0/8" instead
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: warning: mynetworks: non-null host address bits in "127.0.0.1/8", perhaps you should use "127.0.0.0/8" instead
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: NOQUEUE: reject: RCPT from kopano_kopano_spooler_1.kopano_kopano-net[172.19.0.12]: 451 4.3.0 <kopano_kopano_spooler_1.kopano_kopano-net[172.19.0.12]>: Temporary lookup failure; from=<user1@kopano.demo> to=<user1@kopano.demo> proto=ESMTP helo=<spooler.kopano.demo>
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: warning: smtpd_client_event_limit_exceptions: non-null host address bits in "127.0.0.1/8", perhaps you should use "127.0.0.0/8" instead
mail_1                   | Aug  6 08:20:54 mail postfix/smtpd[1765]: disconnect from kopano_kopano_spooler_1.kopano_kopano-net[172.19.0.12] ehlo=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=3/5

```

**Comment by fbartels** [comment]
@martin-schulze-vireso it feels like https://github.com/tomav/docker-mailserver/blob/41921f82aaff9a7150d99d84b0039cdc3b642ff7/target/start-mailserver.sh#L1025 needs and additional  `| grep -v 127.0.0.1`

```
root@mail:/# ip -o -4 addr show type veth | egrep -o '[0-9\.]+/[0-9]+'
127.0.0.1/8
172.21.0.4/16
172.19.0.3/16
root@mail:/# ip -o -4 addr show type veth | egrep -o '[0-9\.]+/[0-9]+' | grep -v 127.0.0.1
172.21.0.4/16
172.19.0.3/16

```

**Comment by martin-schulze-vireso** [comment]
Hm, that is really strange. What system are you running on?
I tested this inside an instance of docker-mailserver:testing and got no 127.0.0.1/8 output. The `type veth` should filter that out already.

Anyways, the error messages hint at another problem: If it is not acceptable to have non null entries after the subnet prefix, the addresses have to be sanitized before passing them on.

**Comment by fbartels** [comment]
my local machine is a 16.04 ubuntu with the official Docker packages

**Comment by fbartels** [comment]
https://github.com/tomav/docker-mailserver/pull/1210 is my pr to improve the current test

**Comment by martin-schulze-vireso** [comment]
With #1215 being merged, could you try that again please?

**Comment by fbartels** [comment]
@martin-schulze-vireso thanks it works now for the above use case
