### ISSUE TITLE
Amavis socket permissions error

### ISSUE THREAD

**Issue by jakehamilton** [tomav/docker-mailserver#1146]
The server fails to start up because there seems to be some permissions issues with `/var/lib/amavis/amavisd.sock`. It also looks like postfix runs into errors with its lock file as well.

## Context
I was trying to spin up an instance of the mail server, but am unable to because of these errors. 

It should be noted that the issue with `amavisd.sock` still occurs when `ENABLE_CLAMAV=0`.

Seemingly permissions based, but you never know. Here is an excerpt from the logs:

<details>
  <summary>Service Log</summary>

  ```
o1rvi6r Mar 22 13:41:22 77fe137209c3 amavis[8242]: (!)Net::Server: 2019/03/22-13:41:22 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:22,669 INFO spawned: 'clamav' with pid 8412
o1rvi6r 2019-03-22 13:41:22,730 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:22,737 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:23,488 INFO spawned: 'clamav' with pid 8537
o1rvi6r 2019-03-22 13:41:23,490 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,491 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:23,526 INFO spawned: 'amavis' with pid 8544
o1rvi6r 2019-03-22 13:41:23,529 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,533 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:23 77fe137209c3 amavis[8397]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:23 77fe137209c3 amavis[8397]: (!)Net::Server: 2019/03/22-13:41:23 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:23,669 INFO spawned: 'clamav' with pid 8568
o1rvi6r 2019-03-22 13:41:23,730 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,735 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:24,612 INFO spawned: 'clamav' with pid 8694
o1rvi6r 2019-03-22 13:41:24,613 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,614 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:24,649 INFO spawned: 'amavis' with pid 8699
o1rvi6r 2019-03-22 13:41:24,657 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,660 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:24 77fe137209c3 amavis[8544]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:24 77fe137209c3 amavis[8544]: (!)Net::Server: 2019/03/22-13:41:24 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:24,669 INFO spawned: 'clamav' with pid 8702
o1rvi6r 2019-03-22 13:41:24,728 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,740 INFO exited: clamav (exit status 1; not expected)
-o1rvi6r 2019-03-22 13:41:25,609 INFO spawned: 'clamav' with pid 8843
o1rvi6r 2019-03-22 13:41:25,611 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,612 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:25,655 INFO spawned: 'amavis' with pid 8850
o1rvi6r 2019-03-22 13:41:25,657 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,661 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:25 77fe137209c3 amavis[8699]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:25 77fe137209c3 amavis[8699]: (!)Net::Server: 2019/03/22-13:41:25 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:25,669 INFO spawned: 'clamav' with pid 8852
o1rvi6r 2019-03-22 13:41:25,742 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,747 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,558 INFO spawned: 'clamav' with pid 8956
o1rvi6r 2019-03-22 13:41:26,613 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,616 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:26 77fe137209c3 postfix/master[8954]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied
o1rvi6r 2019-03-22 13:41:26,669 INFO spawned: 'clamav' with pid 8960
o1rvi6r 2019-03-22 13:41:26,718 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,721 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,778 INFO spawned: 'clamav' with pid 8961
o1rvi6r 2019-03-22 13:41:26,779 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,780 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,803 INFO spawned: 'amavis' with pid 8962
o1rvi6r 2019-03-22 13:41:26,807 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,807 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,808 INFO spawned: 'clamav' with pid 8963
o1rvi6r 2019-03-22 13:41:26,852 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,859 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:30,199 INFO spawned: 'clamav' with pid 9015
  ```

</details>

As well, here is the compose file I'm using to deploy the service:

<details>
  <summary>docker-compose.yml</summary>

```yaml
version: '3.7'

services:
  mail:
    image: tvial/docker-mailserver
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      - target: 995
        published: 995
        protocol: tcp
        mode: host
    volumes:
      - data:/var/mail
      - state:/var/mail-state
      - config:/tmp/docker-mailserver
      - letsencrypt:/etc/letsencrypt
    environment:
      - ENABLE_CLAMAV=1
      - ONE_DIR=1
      - OVERRIDE_HOSTNAME=example.com
      - OVERRIDE_DOMAINNAME=example.com
      - POSTMASTER_ADDRESS=admin@example.com
      - SPOOF_PROTECTION=1
      - PERMIT_DOCKER=network
      - SSL_TYPE=letsencrypt
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - "node.role==worker"

volumes:
  data:
    driver: rexray
  state:
    driver: rexray
  config:
    driver: rexray
  letsencrypt:
    driver: rexray

networks:
  internal:
  proxy:
    external: true
```

</details>

Users, SSL, and DNS have already been configured and I don't think they're the issue. Though, I can provide information on that if we think there's any correlation.

## Expected Behavior
Mail server should start given the compose file above.

## Actual Behavior
The server fails to start and several processes keep restarting after failing.

## Possible Fix
Not sure, but perhaps permission modifications? I tried already making permissions on `amavisd.sock` more permissive, but had no luck.

## Steps to Reproduce

1. Copy the above `docker-compose.yml` file, changing the volume drivers to be appropriate for your system (for simplicity, just removing the `driver: rexray` line is good enough) and either providing certs in the `letsencrypt` volume or disabling SSL for this example. You can also remove the `proxy` network as Docker will complain otherwise.
2. Deploy the service with either `docker stack deploy -c ./docker-compose.yml mail` or `docker-compose up`. My experience comes from deploying the stack to a swarm.
3. Watch the logs on the service (in swarm `docker service logs -f mail_mail`)

## Your Environment

* Amount of RAM available: 1GB
* Mailserver version used: `latest` tag
* Docker version used: `18.06.1-ce` and `18.09.2`
* Environment settings relevant to the config:

```yaml
environment:
      - ENABLE_CLAMAV=1
      - ONE_DIR=1
      - OVERRIDE_HOSTNAME=example.com
      - OVERRIDE_DOMAINNAME=example.com
      - POSTMASTER_ADDRESS=admin@example.com
      - SPOOF_PROTECTION=1
      - PERMIT_DOCKER=network
      - SSL_TYPE=letsencrypt
```

* Any relevant stack traces ("Full trace" preferred):

<details>
  <summary>Service Logs</summary>

  ```
o1rvi6r Mar 22 13:41:22 77fe137209c3 amavis[8242]: (!)Net::Server: 2019/03/22-13:41:22 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:22,669 INFO spawned: 'clamav' with pid 8412
o1rvi6r 2019-03-22 13:41:22,730 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:22,737 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:23,488 INFO spawned: 'clamav' with pid 8537
o1rvi6r 2019-03-22 13:41:23,490 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,491 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:23,526 INFO spawned: 'amavis' with pid 8544
o1rvi6r 2019-03-22 13:41:23,529 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,533 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:23 77fe137209c3 amavis[8397]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:23 77fe137209c3 amavis[8397]: (!)Net::Server: 2019/03/22-13:41:23 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:23,669 INFO spawned: 'clamav' with pid 8568
o1rvi6r 2019-03-22 13:41:23,730 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:23,735 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:24,612 INFO spawned: 'clamav' with pid 8694
o1rvi6r 2019-03-22 13:41:24,613 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,614 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:24,649 INFO spawned: 'amavis' with pid 8699
o1rvi6r 2019-03-22 13:41:24,657 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,660 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:24 77fe137209c3 amavis[8544]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:24 77fe137209c3 amavis[8544]: (!)Net::Server: 2019/03/22-13:41:24 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:24,669 INFO spawned: 'clamav' with pid 8702
o1rvi6r 2019-03-22 13:41:24,728 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:24,740 INFO exited: clamav (exit status 1; not expected)
-o1rvi6r 2019-03-22 13:41:25,609 INFO spawned: 'clamav' with pid 8843
o1rvi6r 2019-03-22 13:41:25,611 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,612 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:25,655 INFO spawned: 'amavis' with pid 8850
o1rvi6r 2019-03-22 13:41:25,657 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,661 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:25 77fe137209c3 amavis[8699]: starting. /usr/sbin/amavisd-new at intergalactic.dev amavisd-new-2.10.1 (20141025), Unicode aware
o1rvi6r Mar 22 13:41:25 77fe137209c3 amavis[8699]: (!)Net::Server: 2019/03/22-13:41:25 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n at line 70 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
o1rvi6r 2019-03-22 13:41:25,669 INFO spawned: 'clamav' with pid 8852
o1rvi6r 2019-03-22 13:41:25,742 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:25,747 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,558 INFO spawned: 'clamav' with pid 8956
o1rvi6r 2019-03-22 13:41:26,613 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,616 INFO exited: clamav (exit status 1; not expected)
o1rvi6r Mar 22 13:41:26 77fe137209c3 postfix/master[8954]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied
o1rvi6r 2019-03-22 13:41:26,669 INFO spawned: 'clamav' with pid 8960
o1rvi6r 2019-03-22 13:41:26,718 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,721 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,778 INFO spawned: 'clamav' with pid 8961
o1rvi6r 2019-03-22 13:41:26,779 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,780 INFO exited: amavis (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,803 INFO spawned: 'amavis' with pid 8962
o1rvi6r 2019-03-22 13:41:26,807 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,807 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:26,808 INFO spawned: 'clamav' with pid 8963
o1rvi6r 2019-03-22 13:41:26,852 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
o1rvi6r 2019-03-22 13:41:26,859 INFO exited: clamav (exit status 1; not expected)
o1rvi6r 2019-03-22 13:41:30,199 INFO spawned: 'clamav' with pid 9015
  ```

</details>

## Finally...
Thank you for all the hard work thus far! ❤️

**Comment by erik-wramner** [comment]
This is an old issue and the code has changed. Is it still relevant, or can it be closed?

**Comment by jakehamilton** [comment]
I ended up using a different solution for my mail server as I couldn't get this to work. Haven't tried it again in the last few months so it is possible that it is fixed.

**Comment by polarathene** [comment]
> after reboot it can't start anymore

`docker compose up --force-recreate` or `docker compose down && docker compose up`, do either of those fix it for you? They're documented early in our [troubleshooting docs page](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/debugging/) for a reason.

You are likely affected by https://github.com/docker-mailserver/docker-mailserver/issues/3280 , following the proper container restart advice will avoid that.

**Comment by Stepyon** [comment]
> `docker compose up --force-recreate` or `docker compose down && docker compose up`, do either of those fix it for you?
Recreation works (I do it in Portainer by pulling and deploying new image) but it is not a solution, I don't want to do it manually every time after server reboots.

**Comment by polarathene** [comment]
> Recreation works (I do it in Portainer by pulling and deploying new image) but it is not a solution

It is a solution, it works. A workaround is still a solution, you get a functional image.

---

> I don't want to do it manually every time after server reboots.

I don't think anybody wants to. If you have the time to contribute the fix we welcome a PR. DMS has a few maintainers, but we're all strapped for time (_probably like yourself_), if you aren't able or interested in resolving it yourself you could try funding a bounty to attract more contributors?

That said as per the docs link, this is a general issue with DMS, so fixing the issue with Amavis resolves that specific one, but if you don't force recreate DMS container, you may get other obscure bugs.

Might be easier to request Portainer or Docker Compose to have a restart policy that force recreates the container? (_doesn't seem that farfetched to want a container that restarts in an immutable fashion, erasing any internal state that isn't persisted through volumes?_)

**Comment by Stepyon** [comment]
> this is a general issue with DMS, so fixing the issue with Amavis resolves that specific one

Ok, I gave it a try and I think the mentioned issue is not related to what I have, I added this condition to misc.sh:
```
    if ! grep -q "smtp-amavis" "/etc/postfix/master.cf"; then
      cat /etc/dms/postfix/master.d/postfix-amavis.cf >>/etc/postfix/master.cf
    fi
```
and checked that **master.cf** doesn't include **postfix-amavis.cf** content twice after restart. So it makes no effect at all and I still have the same issue. It looks like a permissions issue to me (see the logs in prev. message), I also noticed that after container recreation the folders have the following ownership:

```
sv@RPI4:/opt/dms $ ls -la
total 24
drwxr-xr-x  6 sv   sv   4096 Jul 10 10:00 .
drwxr-xr-x 19 sv   sv   4096 Jul 10 00:09 ..
drwxr-xr-x  3 sv   sv   4096 Jun 18 12:37 config
drwxr-xr-x  3 5000 5000 4096 Jun 13 23:57 mail-data
drwxr-xr-x  2  113 root 4096 Jul  7 06:28 mail-logs
drwxr-xr-x 11 sv   sv   4096 Jun 13 23:57 mail-state
```
But after server restart they change to:
```
sv@RPI4:/opt/dms $ ls -la
total 24
drwxr-xr-x  6 sv sv 4096 Jul 10 10:00 .
drwxr-xr-x 19 sv sv 4096 Jul 10 00:09 ..
drwxr-xr-x  3 sv sv 4096 Jun 18 12:37 config
drwxr-xr-x  3 sv sv 4096 Jun 13 23:57 mail-data
drwxr-xr-x  2 sv sv 4096 Jul  7 06:28 mail-logs
drwxr-xr-x 11 sv sv 4096 Jun 13 23:57 mail-state
```

Any ideas?

**Comment by polarathene** [comment]
> and checked that **master.cf** doesn't include **postfix-amavis.cf** content twice after restart.

It was probably fixed indirectly with a [change we added into v14](https://github.com/docker-mailserver/docker-mailserver/pull/3929). We detect early on if the container is restarted and if it is we will skip running most of our startup scripts:

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/start-mailserver.sh#L172-L200

It's possible that this inadvertently causes the issue you're experiencing now though with restarts? You might be able to observe different behaviour by running the prior release `:13.3.1`. Amavis service should be duplicated then, but the permissions issue may no longer be a problem, flipping it around.

---

>  It looks like a permissions issue to me (see the logs in prev. message), I also noticed that after container recreation the folders have the following ownership:

As for the existing concern with file permissions, we call these two methods that would adjust permissions (_but since v14 this will be skipped with container restarts_):

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/start-mailserver.sh#L120-L121

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup.d/mail_state.sh#L3-L8

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup.d/mail_state.sh#L86-L120

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup-stack.sh#L85-L104

You're showing me the ownership of volume dirs from the host. I can see that `mail-data` would be `/var/mail` in the container, that is meant to be `5000:5000` yes:

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup-stack.sh#L90-L93

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/helpers/utils.sh#L69-L81

Why that is unset by a server restart... I am not sure? You have something in your filesystem that is adjusting the ownership back to `sv` unrelated to DMS running? Perhaps this is a remote filesystem?

`mail-logs` likewise would mount to `/var/log/mail` and we set the ownership here:

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup.d/log.sh#L3-L11

I don't think either of those would be related to the Amavis error log which is related to your `mail-state` volume, as shown above, that would be adjusted during fresh container startup:

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/startup/setup.d/mail_state.sh#L92

When you volume mount to `/var/mail-state` we symlink `/var/lib/<service>` to `/var/mail-state/lib-<service>`, just in case the `/var/lib/amavis/` path from the log seemed a mismatch to what we were correcting.

You can probably inspect your local `mail-state` directory and also see permissions have been set to `sv` there too? DMS probably assumes `root` and running Docker as root, but I think you have something external adjusting the ownership here that you'll need to identify? Otherwise the corrected ownership should have been left as-is.

One other way to resolve that would be to ensure we always run the mentioned ownership fixes, even when the DMS container is restarted.

**Comment by Stepyon** [comment]
> You can probably inspect your local `mail-state` directory and also see permissions have been set to `sv` there too?
Yes, they are changing to "sv" as well after reboot, I don't know what does that. It seems to happen to everything I have in "/opt" folder, but for other containers it is not an issue. I tried to google why it might happen but no luck so far...

> Perhaps this is a remote filesystem?
No, this is a USB SSD disc which runs Raspbian OS and Docker with default mounting options in fstab:
` /               ext4    defaults,noatime,discard  0       1`

> One other way to resolve that would be to ensure we always run the mentioned ownership fixes
This should work, is any way I can enable this?
The container survives if I manually stop it and run again or restart, but after reboot the folders permissions are changed and it can't start anymore.

**Comment by polarathene** [comment]
> but after reboot the folders permissions are changed and it can't start anymore.

> It seems to happen to everything I have in "/opt" folder

First try with your volume mounts in another location, like `/example`, just create that location with root and `chown` to your `sv` user, assuming `sv` is your login user (_`id -u` probably says `1000` / `1001`, and that matches with your `sv` user, `grep sv /etc/passwd`_).

If you then reboot, that location should not be applying those changes, if that is happening, whatever is doing it is not hard-coded to specific locations like `/opt`, but it would at least help identify this. You could then remove the `/example` location after that experiment.

Another simple one to try first might just be to skip Portainer, it's possibly trying to be helpful in some way with volumes it knows about.

```bash
docker run --rm -it -v /opt/delete-me:/test --workdir /test alpine ash -c 'touch hello.txt && chown 42:1337 hello.txt'
```

Then when you reboot, the `/opt/delete-me/hello.txt` file should either be set to `sv:sv` ownership or remain as `42:1337`. If it's been changed to `sv:sv`, it is not likely to be Portainer or Compose, so you could then rule those two concerns out.

---

> > One other way to resolve that would be to ensure we always run the mentioned ownership fixes
> 
> This should work, is any way I can enable this?

No not yet, someone would need to contribute this: https://github.com/docker-mailserver/docker-mailserver/issues/4108

Might land for DMS v14.1, depends who has the time to put the PR together.
