### ISSUE TITLE
Mail report sent to wrong address (0@mydomain)

### ISSUE THREAD

**Issue by cybermcm** [tomav/docker-mailserver#1271]
I'm using the mail report feature, worked until a few days back (maybe an update, currently pulling every available version). Now report is sent to 0@mydomain instead of postmaster@mydomain

## Context
Didn't change any setting. Tried to move to the new report settings. With old settings mail was sent to 1@mydomain, now it is sent to 0@mydomain.
Actual mail to postmaster@mydomain is working

## Expected Behavior
report sent to postmaster@mydomain

## Actual Behavior
report not sent because is sent to 0@mydomain

## Possible Fix
found no bug which describes my issue

## Steps to Reproduce
send daily report

## Your Environment
* Amount of RAM available: 12GB
* Mailserver version used: currently latest (2019-09-21)
* Docker version used: Docker version 19.03.2, build 6a30dfc
* Environment settings relevant to the config:
```
mail:
  cap_add:
   - NET_ADMIN # needed by fail2ban inside container
   #- SYS_PTRACE # not clear if needed https://github.com/tomav/docker-mailserver/issues/1057
  container_name: mail
  depends_on:
   - openldap
  domainname: ${hostname}
  env_file: /opt/.env
  environment:
   - DMS_DEBUG=0
   - ENABLE_CLAMAV=1
   - ONE_DIR=1
   - ENABLE_POP3=1
   - ENABLE_FAIL2BAN=1
   - SSL_TYPE=manual
   - SSL_CERT_PATH=${mail_SSL_CERT_PATH}
   - SSL_KEY_PATH=${mail_SSL_KEY_PATH}
   - TLS_LEVEL=modern
   - SPOOF_PROTECTION=1
   - ENABLE_SRS=0
   - PERMIT_DOCKER=network   
   - POSTFIX_MESSAGE_SIZE_LIMIT=30720000
   - ENABLE_MANAGESIEVE=1
   - OVERRIDE_HOSTNAME=${mail_OVERRIDE_HOSTNAME}
   - PFLOGSUMM_TRIGGER=daily_cron
   - LOGWATCH_INTERVAL=daily
   - ENABLE_SPAMASSASSIN=1
   - ENABLE_LDAP=1
   - LDAP_START_TLS=no
   - LDAP_SERVER_HOST=${mail_LDAP_SERVER_HOST}
   - LDAP_SEARCH_BASE=${mail_LDAP_SEARCH_BASE}
   - LDAP_BIND_DN=${mail_LDAP_BIND_DN}
   - LDAP_BIND_PW=${mail_LDAP_BIND_PW}
   - LDAP_QUERY_FILTER_USER=${mail_LDAP_QUERY_FILTER_USER}
   - LDAP_QUERY_FILTER_GROUP=${mail_LDAP_QUERY_FILTER_GROUP}
   - LDAP_QUERY_FILTER_ALIAS=${mail_LDAP_QUERY_FILTER_ALIAS}
   - LDAP_QUERY_FILTER_DOMAIN=${mail_LDAP_QUERY_FILTER_DOMAIN}
   - DOVECOT_USER_FILTER=${mail_DOVECOT_USER_FILTER}
   - DOVECOT_PASS_FILTER=${mail_DOVECOT_PASS_FILTER}
   - ENABLE_POSTGREY=0
   - ENABLE_SASLAUTHD=1
   - SASLAUTHD_MECHANISMS=ldap
   - SASLAUTHD_LDAP_SERVER=${mail_SASLAUTHD_LDAP_SERVER}
   - SASLAUTHD_LDAP_SSL=0
   - SASLAUTHD_LDAP_BIND_DN=${mail_SASLAUTHD_LDAP_BIND_DN}
   - SASLAUTHD_LDAP_PASSWORD=${mail_SASLAUTHD_LDAP_PASSWORD}
   - SASLAUTHD_LDAP_SEARCH_BASE=${mail_SASLAUTHD_LDAP_SEARCH_BASE}
   - SASLAUTHD_LDAP_FILTER=${mail_SASLAUTHD_LDAP_FILTER}
  hostname: ${mail_hostname}
  image: tvial/docker-mailserver
  labels:
   - ${ouro_true}
  networks:
   compose:
    # fixed ip to use it from the host machine
    ipv4_address: 172.18.1.1
  ports:
   - "25:25"
   - "587:587"
   - "993:993"
   - "995:995"
   #- "4190:4190"
  restart: always
  volumes:
   - ${timezone}
   - ${localtime}
   - /opt/_ssl:/tmp/ssl:ro
   - /opt/mail/var:/var/mail
   - /opt/mail/state:/var/mail-state
   - /opt/mail/config:/tmp/docker-mailserver
   - /opt/mail/log:/var/log/mail
   - /opt/mail/opendmarc:/etc/opendmarc
```

* Any relevant stack traces ("Full trace" preferred):
```
mail                    | Sep 21 06:35:18 mail postfix/pickup[8948]: 1FEAA13007A5: uid=0 from=<root>
mail                    | Sep 21 06:35:18 mail postfix/cleanup[13169]: 1FEAA13007A5: message-id=<20190921043518.1FEAA13007A5@mydomain>
mail                    | Sep 21 06:35:18 mail opendkim[1761]: 1FEAA13007A5: no signing table match for 'mailserver-report@mydomain'
mail                    | Sep 21 06:35:18 mail opendkim[1761]: 1FEAA13007A5: no signature data
mail                    | Sep 21 06:35:18 mail postfix/qmgr[2568]: 1FEAA13007A5: from=<root@mydomain>, size=5289, nrcpt=1 (queue active)
mail                    | Sep 21 06:35:18 mail postfix/local[13177]: 1FEAA13007A5: to=<0@mydomain>, orig_to=<0>, relay=local, delay=0.41, delays=0.32/0.06/0/0.03, dsn=5.1.1, status=bounced (unknown user: "0")
mail                    | Sep 21 06:35:18 mail postfix/cleanup[13169]: 7852713007A6: message-id=<20190921043518.7852713007A6@mydomain>
mail                    | Sep 21 06:35:18 mail postfix/bounce[13180]: 1FEAA13007A5: sender non-delivery notification: 7852713007A6
mail                    | Sep 21 06:35:18 mail postfix/qmgr[2568]: 7852713007A6: from=<>, size=7141, nrcpt=1 (queue active)
mail                    | Sep 21 06:35:18 mail postfix/qmgr[2568]: 1FEAA13007A5: removed
mail                    | Sep 21 06:35:18 mail postfix/cleanup[13169]: 7C4EC130073E: message-id=<20190921043518.7852713007A6@mydomain>

```

## Possible answers to you issue
none found

**Comment by erik-wramner** [comment]
This is clearly a bug. I'll fix it, but in the meantime you may want to set REPORT_RECIPIENT or PFLOGSUMM_RECIPIENT and LOGWATCH_RECIPIENT to your postmaster account to get it working. Personally I'm setting REPORT_RECIPIENT which is copied to the other two.

**Comment by erik-wramner** [comment]
This should hopefully be fixed with #1272, which should be in latest shortly.

**Comment by erik-wramner** [comment]
@cybermcm can we close this or do you still have problems?

**Comment by cybermcm** [comment]
I used PFLOGSUMM_RECIPIENT for now -> working;
I'll try latest without PFLOGSUMM_RECIPIENT tonight and will report back

**Comment by cybermcm** [comment]
Mail tonight was again sent to 0@mydomain, but I think I didn't pull the new image yesterday, sorry. I'll try again. Is there a way to manual trigger report creation so that I can test it instantly?

**Comment by cybermcm** [comment]
Hi, just checked, without PFLOGSUMM_RECIPIENT still
```
root@mail:/etc/cron.daily# cat postfix-summary
#!/bin/bash
/usr/local/bin/report-pflogsumm-yesterday mail.mydomain 0 mailserver-report@mydomain
```
with PFLOGSUMM_RECIPIENT
```
root@mail:/etc/cron.daily# cat postfix-summary
#!/bin/bash
/usr/local/bin/report-pflogsumm-yesterday mail.mydomain postmaster@mydomain mailserver-report@mydomain
```
In my point of view still an issue if env var is not set (this time pulled fresh image from hub)

**Comment by erik-wramner** [comment]
Indeed, I hadn't covered that as 0 was supposed to disable reports entirely. An oversight which has hopefully been fixed now with #1273.

**Comment by cybermcm** [comment]
just pulled the newest image -> working again without env var.
Thank you for your help!
