### ISSUE TITLE
Expanded LDAP options

### ISSUE THREAD

**Issue by Fmstrat** [tomav/docker-mailserver#680]
Hi,

I would love to see some expanded LDAP options in the environment variables so we don't need to use custom configuration files when leveraging Active Directory.

Specifically:

For postfix (all three ldap files):
- `LDAP_RESULT_ATTRIBUTE` to set `result_attribute = samaccountname`

For dovecotcat-ldap.conf:
- `DOVECOT_AUTH_BIND` to set `auth_bind = yes`
- `DOVECOT_PASS_ATTRS` to set `pass_attrs = sAMAccountname=user,userPassword=password`
- `DOVECOT_USER_ATTRS` to set `user_attrs = =uid=6000,=gid=6000,=home=/home/DOMAIN/%n,=mail=maildir:/home/DOMAIN/%n/Maildir` (for handling custom virtual mailboxes)

Thanks!

**Comment by Fmstrat** [comment]
An alternative would be to alter the documentation to update documentation to make this easier. For instance, suggest as an option for LDAP configuration to include the following in the `docker-compose.yaml` file:

```
    volumes:
      - ./mail/config/dovecot/dovecot-ldap.conf.ext:/etc/dovecot/dovecot-ldap.conf.ext:ro
      - ./mail/config/postfix/ldap-users.cf:/etc/postfix/ldap-users.cf:ro
      - ./mail/config/postfix/ldap-groups.cf:/etc/postfix/ldap-groups.cf:ro
      - ./mail/config/postfix/ldap-aliases.cf:/etc/postfix/ldap-aliases.cf:ro
    environment:
      - ENABLE_LDAP=1
```

With the AD settings (for Windows or Samba4):

dovecot-ldap.conf.ext:
```
base = cn=Users,dc=<domain>,dc=local
default_pass_scheme = SSHA
dn = cn=<ldapuseroradministrator>,cn=Users,dc=<domain>,dc=local
dnpass = <domainpass>
hosts = <ldaphost>
ldap_version = 3
auth_bind = yes
pass_attrs = sAMAccountname=user,userPassword=password
pass_filter = "(&(objectclass=person)(sAMAccountName=%n))"
user_attrs = =uid=6000,=gid=6000,=home=/home/<DOMAIN>/%n,=mail=maildir:/home/<DOMAIN>/%n/Maildir
user_filter = "(&(objectclass=person)(sAMAccountName=%n))"
```

ldap-*.cf:
```
bind = yes
bind_dn = cn=<ldapuseroradministrator>,cn=Users,dc=<domain>,dc=local
bind_pw = <domainpass>
query_filter = (samaccountname=%s)
result_attribute = samaccountname
search_base = cn=Users,dc=<domain>,dc=local
server_host = <ldaphost>
version = 3
```

This took me a while to figure out, but after I did it worked nicely.

**Comment by alinmear** [comment]
@Fmstrat you can already do this partially (if the keys are already existing within the config files, which is give for your first post) via the two env prefixes:

```bash
LDAP_ 
DOVECOT_
```

you can set them as env variable and the configomat will take care of setting them:

* for postfix ldap parts: https://github.com/tomav/docker-mailserver/blob/9e7959fafef48b0da620d0d04d0a547029785689/target/start-mailserver.sh#L541
* for dovecot: https://github.com/tomav/docker-mailserver/blob/9e7959fafef48b0da620d0d04d0a547029785689/target/start-mailserver.sh#L560

**NOTE**: You can specify any key within the ldap configs prefixed and uppercased

**Comment by Fmstrat** [comment]
I don't think this will work for all features. For instance, in the ldap-* files setting `result_attribute = samaccountname` is not possible with the current `LDAP_*` mappings because it is not in the main postfix `main.cf` file. That being said, the above PR would help solve things allowing us to run a simple `sed` command to make the change.

**Comment by alinmear** [comment]
@Fmstrat maybe I am not getting this right, but did you sort the start-mailserver.sh script? The parts i linked above are only for the files:

`for f in /etc/postfix/ldap-users.cf /etc/postfix/ldap-groups.cf /etc/postfix/ldap-aliases.cf`

So it would be possible to specifiy the `result_attribute` key, because it's within the default configs. The implementation is not working for keys, that are not available within the config; so the configomat would only substitute existing keys not is currently not specifying new values, like e.g. postmap is doing it. 

So what am i missing?

**Comment by Fmstrat** [comment]
Ahhhhh.. I had not realized this. I will dive into that to see if I can make it all work.

Also, is there aconfigmap.sh for `POSTFIX_` would allow further custom configuration within postfix?

**Comment by alinmear** [comment]
@Fmstrat not like this. Because there are 2 config paradigmas at this time within the project. Both have their benefits.

First paradigma: provide config files
Second paradigma: specify config via env variables

Actually the postfix main.cf is accessed via the first pardigma; provide /tmp/docker-mailserver/postfix-main.cf at container startup and each lined will be issued by `postconf -e $line`.

Maybe we could discuss refactoring the start-mailserver.sh script, that both paradigmas would be covered. But the configomat at this time (little project by myself, only issuing a sed call and taking care that special character will be threaded the right way) is not supporting postconf, neither it is intended to. 

But this should be discussed separately.

Thx for your interest and contribution so far. Hopefully we gonna make this project even better!

**Comment by BirgerK** [comment]
So, is there a recommended way to define all those ldap config files with custom values?

I'm not sure if this issue has a result.... But I'm pretty interested in it!

**Comment by BirgerK** [comment]
I'm trying to set some Dovecot parameters by environment variables:
```
DOVECOT_HOSTS: "myMagicLdap"
DOVECOT_PASS_ATTRS: "uid=user,userPassword=password"
DOVECOT_PASS_FILTER: "(&(objectClass=mailAccount)(uid=%n))"
DOVECOT_USER_ATTRS: "=home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir"
DOVECOT_USER_FILTER: "(&(objectClass=mailAccount)(uid=%n))"
```

But the configomat breaks with the message:
```
/usr/local/bin/configomat.sh: line 29: config_overrides[$key]: bad array subscript
```

Not sure what it means, but seems like the configuration of dovecot by environment variables isn't that generic. What's wrong?

**Comment by alinmear** [comment]
Hm, will try to investigate, what's happening here

**Comment by johansmitsnl** [comment]
Is this solved?

**Comment by BirgerK** [comment]
I don't think so, no.

I tried to set the expanded LDAP options, but an error got thrown. @alinmear wanted to investigate this, and I'm waiting for this. :)

**Comment by alinmear** [comment]
@BirgerK i fixed the problem within the configomat. Can you retry please and leave some comment for feedback, thx!

**Comment by johansmitsnl** [comment]
Updated the branch, master is building. Could you verify if it works and reopen if not?

**Comment by dasmaeh** [comment]
```
DOVECOT_USER_ATTRS: "=home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir"
```
fails but 
```
DOVECOT_USER_ATTRS: "/var/mail/%{ldap:mail}=home, maildir:/var/mail/%{ldap:mail}/Maildir=mail"
```
seems to work well.

**Comment by BirgerK** [comment]
I checked it on my site.

It's still the same problem, like reported [before](https://github.com/tomav/docker-mailserver/issues/680#issuecomment-361277981).

The exception still is:
```
/usr/local/bin/configomat.sh: line 29: config_overrides[$key]: bad array subscript
```

**Comment by johansmitsnl** [comment]
@BirgerK please open the issue https://github.com/alinmear/docker-configomat

**Comment by BirgerK** [comment]
@johansmitsnl The image is still using the old configmat version.

The submodule (see [the repo](https://github.com/tomav/docker-mailserver/tree/master/target)) is pointing to the commit `e3e84de` but it should be `e78eb3a14bff048bf1d74c0f8d5a6fbb1438c8f7`.
