### ISSUE TITLE
Can't send

### ISSUE THREAD

**Issue by mzedeler** [tomav/docker-mailserver#854]
My mailserver upgrades with the latest docker image now and then. Now it has suddenly stopped accepting ingoing mail. The logs are full of this:

    Feb 19 16:39:30 ip-10-0-1-60 docker[1015]: Feb 19 16:39:30 8e55eafcefa9 postfix/smtpd[1213]: Anonymous TLS connection established from mailrelay2-2.pub.mailoutpod1-cph3.one.com[46.30.212.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
    Feb 19 16:39:31 ip-10-0-1-60 docker[1015]: Feb 19 16:39:31 8e55eafcefa9 postfix/smtpd[1213]: warning: connect to TCP map localhost:10002: Cannot assign requested address
    Feb 19 16:39:32 ip-10-0-1-60 docker[1015]: Feb 19 16:39:32 8e55eafcefa9 postfix/smtpd[1213]: warning: connect to TCP map localhost:10002: Cannot assign requested address

It seems that some service running on port 10002 has died.

**Comment by boaorm** [comment]
Do you have `postfix-send-access.cf` and `postfix-receive-access.cf` in the config dir? If you don't create those two files (they can be empty) and see if it works again.

**Comment by johansmitsnl** [comment]
@boaorm this is fixed in: 5e09074d587114ef4d771fe65c911b67735d4fcb

**Comment by boaorm** [comment]
Great, I did a reinstall today and had to add those two files to get it up an running.

**Comment by mzedeler** [comment]
@johansmitsnl - I have both files and they are both empty:

    ls -l *access*
    -rw-rw-rw-. 1 root root 1 Feb 19 15:56 postfix-receive-access.cf
    -rw-rw-rw-. 1 root root 1 Feb 19 15:57 postfix-send-access.cf

I tired pulling the latest image and the problem is still there.

**Comment by mzedeler** [comment]
It seems that `postsrsd` just dies without any log output:

    root@37b79c4bfa86:/# supervisorctl start postsrsd
    postsrsd: started
    root@37b79c4bfa86:/# ps axguww | grep posts
    postfix   1089  0.0  0.3  87644  3520 ?        Ss   09:04   0:00 postscreen -l -n smtp -t inet -u -s 2
    root      3052  0.0  0.0  11116   972 pts/0    S+   09:13   0:00 grep posts

**Comment by mzedeler** [comment]
What causes this seems to be this line in `/etc/init.d/postsrsd`:

    test -r "$SRS_SECRET" -a -n "$SRS_DOMAIN" || exit 0

**Comment by mzedeler** [comment]
I've been doing some more digging and it seems that `postconf -h mydomain` doesn't return anything when run by the init script. It works from the command line.

**Comment by mzedeler** [comment]
I found the source of the bug - in /etc/default/postsrsd:

   SRS_DOMAIN=

But this is sourced *after* the defaults provided by the init script, so this empty value overrides the one set in the init script:

```
# Default configuration
SRS_DOMAIN=`postconf -h mydomain || true`
SRS_FORWARD_PORT=10001
SRS_REVERSE_PORT=10002
SRS_SECRET=/etc/postsrsd.secret
SRS_SEPARATOR==
RUN_AS=postsrsd
CHROOT=/var/lib/postsrsd

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
    . /etc/default/$NAME
fi
```

**Comment by mzedeler** [comment]
And I tracked this back to:

    DOMAINNAME="$(hostname -d)"
    sed -i -e "s/localdomain/$DOMAINNAME/g" /etc/default/postsrsd

In ` postsrsd-wrapper.sh`.

**Comment by mzedeler** [comment]
I found the issue: I'm running this without `docker-compose`, so I needed to add the flag `--hostname <my.host.name>` to make it work.

**Comment by mzedeler** [comment]
It would be nice if there was a more explicit error message somewhere. I don't mind writing a patch for this. How about adding it to the postsrsd wrapper script?

**Comment by mzedeler** [comment]
@johansmitsnl

**Comment by johansmitsnl** [comment]
@mzedeler it is a good location to add it to the wrapper script. If you provide a patch I'll look in to it and merge it.
